# Generated by Django 5.0.6 on 2024-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_news_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
